### ISSUE TITLE
Money and Exp upper limit not being obeyed

### ISSUE THREAD

**Issue by neokyle** [Codisimus/PhatLoots#20] opened 2015-08-13 09:25 UTC
The upper limit for both money and exp is not being obeyed. Here is a sample from one of my loot tables.

  LootList:
  - ==: LootCollection
    LootList:
    - ==: Money
      Lower: 200
      Probability: 60.0
      Upper: 1000
    - ==: Experience
      Lower: 400
      Probability: 60.0
      Upper: 700

When looting the chest with these rewards the upper limit can be exceeded by double. A majority of lootings don't have this issue, however occasionally it will surpass the upper limit.

I'm using phatloots 4.1.0 on the latest spigot 1.8 build. Using vault and essentials for the economy.

**Comment by neokyle** [comment] 2015-08-14 07:20
Upon further testing I've discovered another issue possibly related to this one. I set the upper limit and lower limit for exp and money to the same numbers. 1000 for money, and 700 for exp. I then used /loot reload and tested my phatloot to see if the issue I originally reported persisted. It did, but this time the issue seems to have been made clearer. For money with the upper and lower limit set to 1000 I would usually get 1000, but sometimes I would get 2000. I noticed that occasionally I would also get 1000 for exp even though the upper and lower limit for exp were both set to 700.

**Comment by neokyle** [comment] 2015-08-14 10:07
After more testing it seems to only be an issue with money loot in collections.

**Comment by Codisimus** [comment] 2016-02-25 01:43
Could you please paste an example of a PhatLoot save file which has this problem?

**Comment by Codisimus** [comment] 2016-04-09 21:02
Closed as cannot reproduce. If this continues to happen please create a new ticket.

**Closed by Codisimus** 2016-04-09 21:02 UTC
Labels: bug, cannot reproduce
